### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Noni86kg**

### CODE REVIEW

**Comment by ghost** [comment]
On change check email again, and remove the error message if the email is valid.
image
Reduce the size of the error message.

**Comment by Noni86kg** [comment]
I made the changes you requested.
Best regards, Nikola Pavlovic

**Comment by ghost** [comment]
image
Validation does not work at all now. Check.

**Comment by Noni86kg** [comment]
My bad, I corrected the mistakes from both tasks (zadatak 3, bonus zadatak
3).
Best regards, Nikola Pavlovic.

**Pull request merged**
